config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  # TODO EXCEPT
  resources :users
  get 'rsvp' => "users#rsvp", as: :rsvp

  # TODO EXCEPT
  resources :gifts
  post 'claim/:gift_id' => "gifts#claim", as: :claim
  post 'unclaim/:gift_id' => "gifts#unclaim", as: :unclaim

  resources :user_sessions
  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  get 'info' => 'pages#events', as: :events
  get 'admin' => 'pages#admin', as: :admin
  get 'people' => 'pages#people', as: :people

  get "/404", :to => "errors#not_found"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_flash.html.erb
<% flash.each do |status, message| %>
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-push-2">
      <div class="alert <%= css_for_flash(status.to_sym) %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= message %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="row">
  <nav class="main-navbar navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#wedding-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("love-mischief-white.png", height: "35"), root_path, class: "navbar-brand visible-xs" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="wedding-navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "ADMIN", admin_path, class: "header-offset visible-xs" if current_user.admin? %></li>
        <li><%= link_to "INFO", events_path, class: "#{navbar_active("info")} header-offset" %></li>
        <li><%= link_to "PEOPLE", people_path, class: "#{navbar_active("people")} header-offset" %></li>
        <li class="hidden-xs hidden-sm"><%= link_to image_tag("love-mischief-white.png", height: "72"), root_path %></li>
        <li><%= link_to "RSVP", rsvp_path, class: "#{navbar_active("rsvp")} header-offset" %></li>
        <li><%= link_to "REGISTRY", gifts_path, class: "#{navbar_active("registry")} header-offset" %></li>
        <li><%= link_to "LOG OUT", logout_path, method: :post, class: "header-offset visible-xs" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <%= link_to "ADMIN", admin_path, id: "admin", class: "hidden-xs" if current_user.admin? %>
    <%= link_to "LOG OUT", logout_path, method: :post, id: "logout", class: "hidden-xs" %>
  </div>
  </nav>
</div>