config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  # TODO EXCEPT
  resources :users
  get 'rsvp' => "users#rsvp", as: :rsvp

  # TODO EXCEPT
  resources :gifts
  post 'claim/:gift_id' => "gifts#claim", as: :claim
  post 'unclaim/:gift_id' => "gifts#unclaim", as: :unclaim

  resources :user_sessions
  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  get 'info' => 'pages#events', as: :events
  get 'admin' => 'pages#admin', as: :admin
  get 'people' => 'pages#people', as: :people

  get "/404", :to => "errors#not_found"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/pages/_bridal_party_member.html.erb
<div class="person-wrapper col-xs-12 col-sm-6">
  <div class="person row">
    <div class="col-xs-12">
      <%= image_tag(bridal_party_member.pic_name, class: "img-responsive img-circle") %>
    </div>
    <div class="col-xs-12">
      <h2><%= bridal_party_member.name %></h2>
      <em class="text-muted"><small><%= bridal_party_member.relation %></small></em>
      <p><%= bridal_party_member.description %></p>
    </div>
  </div>
</div>

app/views/pages/_bridal_party_side.html.erb
<div class="col-xs-12 col-sm-6">
  <div class="info-box">
    <div class="info-box-title">
      <%= title %>
    </div>
    <div class="info-box-info">
      <div class="row">
        <%= render partial: "bridal_party_member", collection: people %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_event.html.erb
<div class="<%= event_width_for(width) %>">
  <div class="info-box">
    <div class="info-box-title"><%= event.title %></div>
    <div class="info-box-info align-left">
      <div class="row">
        <div class="col-xs-12">
          <div class="event">
            <% if event.coming_soon %>
              <h1 class="no-border">Info Coming Soon!</h1>
            <% else %>
              <div class="col-xs-12 col-sm-7 col-sm-push-5">
                <%= image_tag(event.pic_name, class: "img-responsive img-circle") %>
              </div>
              <div class="col-xs-12 col-sm-5 col-sm-pull-7 align-left">
                <% if event.date %>
                  <h3>Date</h3>
                  <p><%= event.date %></p>
                <% end %>
                <% if event.time %>
                  <h3>Time</h3>
                  <p><%= event.time %></p>
                <% end %>
                <% if event.location %>
                  <h3>Location</h3>
                  <p><%= link_to (event.location).html_safe, event.map, target: :_blank %></p>
                <% end %>
                <% if event.contact_phone %>
                  <h3>Phone</h3>
                  <p><%= event.contact_phone %></p>
                <% end %>
              </div>
              <% if event.notes %>
                <div class="col-xs-12 align-left">
                  <h4>Notes</h4>
                  <p><%= (event.notes).html_safe %></p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_events_navbar.html.erb
<div class="row">
  <nav class="navbar secondary-navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#secondary-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand visible-xs">EVENTS</div>
    </div>
    <div id="secondary-navbar-collapse" class="collapse navbar-collapse align-center">
      <ul id="secondary-menu" class="nav navbar-nav">
        <li class="active"><%= link_to "WEDDING DAY", "#wedding-day" %></li>
        <li><%= link_to "HOTEL", "#hotel" %></li>
        <% if current_user.rehearsal_info? %>
          <li><%= link_to "REHEARSAL", "#rehearsal" %></li>
        <% end %>
        <% if current_user.shower_info? %>
          <li><%= link_to "SHOWER", "#shower" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </nav>
</div>

app/views/pages/_user.html.erb
<li>
<%= link_to user_on_admin_page(user), edit_user_path(user) %>
<%= simple_format(user.attendees, {class: "user-guest-list", style: "margin-left: 20px"}) if user.attending? %>
</li>

app/views/pages/admin.html.erb
<div class="container-fluid">
  <%= render "shared/navbar" %>
  <div class="row">
    <div class="col-xs-12 col-md-2">
      <div class="info-box">
        <div class="info-box-title">
          Quick Links
        </div>
        <div class="info-box-info">
          <ul class="quick-links">
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Add Gift", new_gift_path %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-10">
      <div class="info-box">
        <div class="info-box-title">
          Admin Panel
        </div>
        <div class="info-box-info">
          <%= render "shared/flash" %>
          <div class="row">
            <div class="col-xs-12 col-sm-4">
              <h1 class="huge"><%= total_attending(@attending) %></h1>
              <h2 class="no-border">Attending</h2>
              <%= link_to "Toggle Guest List", "#", id: "guest-list-toggle", class: "btn btn-primary" %>
              <ul class="align-left">
                <%= render partial: "user", collection: @attending %>
              </ul>
            </div>
            <div class="col-xs-12 col-sm-4">
              <h1 class="huge"><%= @not_attending.count %></h1>
              <h2 class="no-border">Regrets</h2>
              <ul class="align-left">
                <%= render partial: "user", collection: @not_attending %>
              </ul>
            </div>
            <div class="col-xs-12 col-sm-4">
              <h1 class="huge"><%= @unknown.count %></h1>
              <h2 class="no-border">Unknown</h2>
              <ul class="align-left">
                <%= render partial: "user", collection: @unknown %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/events.html.erb
<% content_for :navigation do %>
  <%= render "events_navbar" %>
  <%= render "shared/navbar" %>
<% end %>
<div class="wrapper-with-navbar">
  <div class="col-xs-12">
    <div id="events">
      <div id="fullpage">
        <div class="row section active" id="wedding-day">
          <%= render partial: "event", locals: { event: @wedding, width: 2 } %>
          <%= render partial: "event", locals: { event: @reception, width: 2 } %>
        </div>
        <div class="row section" id="hotel">
          <%= render partial: "event", locals: { event: @hotel, width: 1 } %>
        </div>
        <% if current_user.rehearsal_info? %>
          <div class="row section" id="rehearsal">
            <%= render partial: "event", locals: { event: @rehearsal, width: current_user.rehearsal_count } if current_user.rehearsal? %>
            <%= render partial: "event", locals: { event: @rehearsal_dinner, width: current_user.rehearsal_count } if current_user.rehearsal_dinner? %>
          </div>
        <% end %>
        <% if current_user.shower_info? %>
          <div class="row section" id="shower">
            <%= render partial: "event", locals: { event: @chicago_shower, width: current_user.shower_count } if current_user.chicago_shower? %>
            <%= render partial: "event", locals: { event: @tipton_shower, width: current_user.shower_count } if current_user.tipton_shower? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<% content_for :navigation do %>
  <%= render "shared/navbar" %>
<% end %>
<div class="wrapper">
  <div class="col-xs-12">
    <div class="row">
      <div class="col-md-8 col-md-push-4 col-sm-12">
        <div class="index-gallery">
          <div class="row">
            <div class="col-sm-4 col-xs-12">
              <div class="info-box-image">
                <%= image_tag("lydia.jpg", class: "align-center img-responsive img-circle") %>
              </div>
              <div class="info-box">
                <div class="info-box-title">
                  Bride
                </div>
                <div class="info-box-info">
                  Lydia<br/>Mikkael
                </div>
              </div>
            </div>
            <div class="col-sm-4 col-xs-12">
              <div class="info-box-image">
                <%= image_tag("john.jpg", class: "align-center img-responsive img-circle") %>
              </div>
              <div class="info-box">
                <div class="info-box-title">
                  Groom
                </div>
                <div class="info-box-info">
                  John<br/>Donald
                </div>
              </div>
            </div>
            <div class="col-sm-4 col-xs-12">
              <div class="info-box-image">
                <%= image_tag("lydia-and-john.jpg", class: "align-center img-responsive img-circle") %>
              </div>
              <div class="info-box">
                <div class="info-box-title">
                  Location
                </div>
                <div class="info-box-info">
                  St. James Church<br/>Arlington Hts. IL
                </div>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="info-box">
                <div class="info-box-title">
                  Sacrament of Holy Matrimony
                </div>
                <div class="info-box-info wedding-date">
                  3:00pm&emsp;December 19th, 2015
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-md-pull-8 col-sm-12">
        <div class="info-box" id="poem">
          <div class="info-box-title">
            The Seed Cracked Open
          </div>
          <div class="info-box-info">
            <p>It used to be<br/>
            That when I would wake in the morning<br/>
            I could with confidence say<br/>
            "What am 'I' going to Do?"</p>

            <p>That was before the seed<br/>
            Cracked open.</p>

            <p>Now Hafiz is certain:</p>

            <p>There are two of us housed<br/>
            In this body.</p>

            <p>Doing the shopping together in the market and<br/>
            Tickling each other<br/>
            While fixing the evening's food.</p>

            <p>Now when I awake</br>
            All the internal instruments play the same music:</p>

            <p>"God, what <strong>love-mischief</strong> can 'We' do<br/>
            For the world<br/>
            Today?"</p>

            <p id="author">--<em>Hafiz</em></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/people.html.erb
<% content_for :navigation do %>
  <%= render "shared/navbar" %>
<% end %>
<div class="wrapper">
  <div class="people">
    <%= render partial: "bridal_party_side", locals: { title: "Bridesmaids", people: @bridesmaids } %>
    <%= render partial: "bridal_party_side", locals: { title: "Groomsmen", people: @groomsmen } %>
  </div>
</div>