config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  # TODO EXCEPT
  resources :users
  get 'rsvp' => "users#rsvp", as: :rsvp

  # TODO EXCEPT
  resources :gifts
  post 'claim/:gift_id' => "gifts#claim", as: :claim
  post 'unclaim/:gift_id' => "gifts#unclaim", as: :unclaim

  resources :user_sessions
  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  get 'info' => 'pages#events', as: :events
  get 'admin' => 'pages#admin', as: :admin
  get 'people' => 'pages#people', as: :people

  get "/404", :to => "errors#not_found"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    if @user = login(params[:username], params[:password].downcase, params[:remember_me])
      redirect_back_or_to(root_path)
    else
      flash.now[:danger] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_path)
  end
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post, class: "form-horizontal" do %>
  <div class="form-group">
    <%= label_tag :username, "Username", class: "col-sm-3 col-xs-12 control-label" %>
    <div class="col-sm-9 col-xs-12">
      <%= text_field_tag :username, nil, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :password, "Password", class: "col-sm-3 col-xs-12 control-label" %>
    <div class="col-sm-9 col-xs-12">
      <%= password_field_tag :password, nil, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :remember_me, "Remember Me", class: "col-sm-3 col-xs-12 control-label" %>
    <div class="col-sm-9 col-xs-12 align-left">
      <%= check_box_tag :remember_me, true, class: "form-control checkbox-fix" %>
    </div>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="login-wrapper">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <div class="info-box">
      <div class="info-box-title">
        Login
        <%= image_tag("love-mischief-white.png", height: "35", class: "pull-right") %>
      </div>
      <div class="info-box-info">
        <%= render "shared/flash" %>
        <div class="row">
          <div class="col-xs-12">
            <div class="wedding-form">
              <%= render "form" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>